
package org.example.client;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "AbsenceService", targetNamespace = "http://service.example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AbsenceService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "update", targetNamespace = "http://service.example.org/", className = "org.example.client.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://service.example.org/", className = "org.example.client.UpdateResponse")
    @Action(input = "http://service.example.org/AbsenceService/updateRequest", output = "http://service.example.org/AbsenceService/updateResponse")
    public void update(
        @WebParam(name = "arg0", targetNamespace = "")
        Etudiant arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://service.example.org/", className = "org.example.client.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://service.example.org/", className = "org.example.client.AddResponse")
    @Action(input = "http://service.example.org/AbsenceService/addRequest", output = "http://service.example.org/AbsenceService/addResponse")
    public void add(
        @WebParam(name = "arg0", targetNamespace = "")
        Etudiant arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "read", targetNamespace = "http://service.example.org/", className = "org.example.client.Read")
    @ResponseWrapper(localName = "readResponse", targetNamespace = "http://service.example.org/", className = "org.example.client.ReadResponse")
    @Action(input = "http://service.example.org/AbsenceService/readRequest", output = "http://service.example.org/AbsenceService/readResponse")
    public double read(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://service.example.org/", className = "org.example.client.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://service.example.org/", className = "org.example.client.DeleteResponse")
    @Action(input = "http://service.example.org/AbsenceService/deleteRequest", output = "http://service.example.org/AbsenceService/deleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTauxAbsenceByCne", targetNamespace = "http://service.example.org/", className = "org.example.client.GetTauxAbsenceByCne")
    @ResponseWrapper(localName = "getTauxAbsenceByCneResponse", targetNamespace = "http://service.example.org/", className = "org.example.client.GetTauxAbsenceByCneResponse")
    @Action(input = "http://service.example.org/AbsenceService/getTauxAbsenceByCneRequest", output = "http://service.example.org/AbsenceService/getTauxAbsenceByCneResponse")
    public double getTauxAbsenceByCne(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.example.client.Etudiant>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "blackListCreate", targetNamespace = "http://service.example.org/", className = "org.example.client.BlackListCreate")
    @ResponseWrapper(localName = "blackListCreateResponse", targetNamespace = "http://service.example.org/", className = "org.example.client.BlackListCreateResponse")
    @Action(input = "http://service.example.org/AbsenceService/blackListCreateRequest", output = "http://service.example.org/AbsenceService/blackListCreateResponse")
    public List<Etudiant> blackListCreate(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
