
package org.example.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "AbsenceServiceImplService", targetNamespace = "http://ws.example.org/", wsdlLocation = "http://localhost:8090/absenceService?wsdl")
public class AbsenceServiceImplService
    extends Service
{

    private final static URL ABSENCESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ABSENCESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ABSENCESERVICEIMPLSERVICE_QNAME = new QName("http://ws.example.org/", "AbsenceServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/absenceService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ABSENCESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ABSENCESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public AbsenceServiceImplService() {
        super(__getWsdlLocation(), ABSENCESERVICEIMPLSERVICE_QNAME);
    }

    public AbsenceServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ABSENCESERVICEIMPLSERVICE_QNAME, features);
    }

    public AbsenceServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, ABSENCESERVICEIMPLSERVICE_QNAME);
    }

    public AbsenceServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ABSENCESERVICEIMPLSERVICE_QNAME, features);
    }

    public AbsenceServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AbsenceServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AbsenceService
     */
    @WebEndpoint(name = "AbsenceServiceImplPort")
    public AbsenceService getAbsenceServiceImplPort() {
        return super.getPort(new QName("http://ws.example.org/", "AbsenceServiceImplPort"), AbsenceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AbsenceService
     */
    @WebEndpoint(name = "AbsenceServiceImplPort")
    public AbsenceService getAbsenceServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.example.org/", "AbsenceServiceImplPort"), AbsenceService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ABSENCESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw ABSENCESERVICEIMPLSERVICE_EXCEPTION;
        }
        return ABSENCESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
